### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by tmsimont** [Sitefinity-SDK/Telerik.Sitefinity.Samples.Jobs#5]
I followed the instructions in the readme and I get the following error when trying to build:

```
The type microsoft.identitymodel.web.httpmodulebase is defined in an assembly that is not referenced
```

in SampleUtilities.cs

**Comment by vladivasilev** [comment]
Please make sure you have Microsoft.IdentityModel.dll in the bin folder. 
You can also check the following KB article: http://www.sitefinity.com/developer-network/knowledge-base/getting-type-is-not-resolved-for-member-microsoft-identitymodel-claims-claimsprincipal-exception

**Comment by tmsimont** [comment]
The dll is in /SitefinityWebApp but not in /Telerik.Sitefinity.Samples.Common

It's the Telerik.Sitefinity.Samples.Common project that seems to be unable to build. 

I installed Windows Identify Foundation with NuGet and it seems OK now
